@kozy_api_HostAddress = http://localhost:5230/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3NTg2MDE5MjIsImV4cCI6MTc1ODYwNTUyMiwiaWF0IjoxNzU4NjAxOTIyLCJpc3MiOiJZb3VySXNzdWVyIiwiYXVkIjoiWW91ckF1ZGllbmNlIn0.13SWgkpqk-sbYKuzzUlcwDDICaQ_NQF7CJf3MbJXMMY

### 1.1. Register
POST {{kozy_api_HostAddress}}/auth/register
Content-Type: application/json

{
  "email": "admin@gmail.vn",
  "password": "Admin@123"
}

### 1.2. Login
POST {{kozy_api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.vn",
  "password": "Admin@123"
}

### 1.3. Get All Users
GET {{kozy_api_HostAddress}}/auth
Authorization: Bearer {{token}}
Content-Type: application/json

